spring:
  application:
    name: springboot-practice

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:4306/test
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 100

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: debug
#    org.hibernate.orm.jdbc.bind: trace
#    org.mariadb.jdbc: debug